/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "background": "#0e0e0e",
        "on-secondary-fixed": "#500086",
        "on-tertiary": "#006165",
        "error-container": "#9f0519",
        "surface-container-low": "#131313",
        "tertiary": "#a1faff",
        "on-surface": "#ffffff",
        "on-secondary-fixed-variant": "#7900c6",
        "surface": "#0e0e0e",
        "on-primary-fixed-variant": "#004c5d",
        "on-error": "#490006",
        "surface-container": "#1a1919",
        "tertiary-fixed-dim": "#00e5ee",
        "on-tertiary-container": "#00575b",
        "surface-bright": "#2c2c2c",
        "on-primary": "#004c5e",
        "secondary-fixed": "#e7c5ff",
        "surface-container-highest": "#262626",
        "on-primary-fixed": "#002c37",
        "on-secondary-container": "#fff5ff",
        "outline": "#777575",
        "inverse-surface": "#fcf8f8",
        "on-secondary": "#340059",
        "on-background": "#ffffff",
        "primary": "#6dddff",
        "surface-dim": "#0e0e0e",
        "tertiary-container": "#00f4fe",
        "primary-fixed-dim": "#00c3eb",
        "inverse-primary": "#00687e",
        "secondary": "#c47fff",
        "tertiary-fixed": "#00f4fe",
        "secondary-container": "#8c00e5",
        "on-error-container": "#ffa8a3",
        "surface-container-lowest": "#000000",
        "primary-fixed": "#00d2fd",
        "surface-container-high": "#201f1f",
        "tertiary-dim": "#00e5ee",
        "surface-tint": "#6dddff",
        "primary-dim": "#00c3eb",
        "on-surface-variant": "#adaaaa",
        "on-primary-container": "#004352",
        "error": "#ff716c",
        "on-tertiary-fixed-variant": "#006266",
        "secondary-dim": "#a533ff",
        "surface-variant": "#262626",
        "secondary-fixed-dim": "#ddb3ff",
        "on-tertiary-fixed": "#004346",
        "inverse-on-surface": "#565554",
        "outline-variant": "#494847",
        "error-dim": "#d7383b",
        "primary-container": "#00d2fd"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "fontFamily": {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
